# Generated by Django 5.2.7 on 2025-11-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("date_start", models.CharField(blank=True, max_length=32, null=True)),
                ("date_end", models.CharField(blank=True, max_length=32, null=True)),
                ("location", models.CharField(blank=True, max_length=120, null=True)),
                ("price_min", models.FloatField(blank=True, null=True)),
                ("price_max", models.FloatField(blank=True, null=True)),
                (
                    "age_restriction",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("ai_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
