# Generated by Django 5.2.7 on 2025-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ai_tags",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
