# Generated by Django 5.2.7 on 2025-10-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_delete_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_preference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.CharField(choices=[('party', 'Party'), ('club', 'Club'), ('concert', 'Concert'), ('festival', 'Festival'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
