# Generated by Django 5.2.7 on 2025-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_custom_preference_profile_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='custom_preference',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='profile',
            name='presets',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
