# Generated by Django 5.2.6 on 2025-09-27 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('integer', 'Integer'), ('float', 'Float'), ('string', 'String'), ('boolean', 'Boolean')], max_length=50)),
                ('value', models.TextField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='map_app.map')),
            ],
        ),
    ]
